### ISSUE TITLE
Trial setup

### ISSUE THREAD

**Issue by hoijui** [OPEN-NEXT/LOSH-Reporter#9]
Moe and me tried in parallel, to get the reporter running on our two machines, according to [the README of `konekto/LOSH-Reporter/dev`](https://github.com/konekto/LOSH-Reporter/tree/dev):

```bash
$ git clone git@github.com:konekto/LOSH-Reporter.git
$ cd LOSH-Reporter
$ # We had pandoc already installed, and installed poetry with:
$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
$ poetry --version
Poetry version 1.1.13
$ poetry shell

  RuntimeError

  Poetry could not find a pyproject.toml file in /bla/LOSH-Reporter or its parents
$ # Because we were on the `master` branch, so:
$ git checkout dev
$ poetry shell
source /home/bla/.cache/pypoetry/virtualenvs/losh-reporter--EO10kDI-py3.9/bin/activate.fish
Argument is not a number: ''
$ # <- error because I was in the fish shell; switching to BASH ...
$ bash
$ poetry shell
$ # Good this time!
$ poetry run python reporter/cli.py --log_to console --out output generate example html
...
please set environment variables for apache fuseki
...
$ # There was a mention in the erorr message about the file '.env.example', nice! :-)
$ cat .env.example
FUSEKI_URL=http://localhost:3030
FUSEKI_DATASET_NAME=loshrdf
$ export FUSEKI_URL=http://localhost:3030
$ export FUSEKI_DATASET_NAME=loshrdf
$ # and we try again ...
$ poetry run python reporter/cli.py --log_to console --out output generate example html
Traceback (most recent call last):
  File "/home/USER/.cache/pypoetry/virtualenvs/losh-reporter--EO10kDI-py3.9/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/USER/.cache/pypoetry/virtualenvs/losh-reporter--EO10kDI-py3.9/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/USER/.cache/pypoetry/virtualenvs/losh-reporter--EO10kDI-py3.9/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USER/.cache/pypoetry/virtualenvs/losh-reporter--EO10kDI-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/USER/.cache/pypoetry/virtualenvs/losh-reporter--EO10kDI-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/USER/.cache/pypoetry/virtualenvs/losh-reporter--EO10kDI-py3.9/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/home/USER/.cache/pypoetry/virtualenvs/losh-reporter--EO10kDI-py3.9/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/USER/.cache/pypoetry/virtualenvs/losh-reporter--EO10kDI-py3.9/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc234802250>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USER/.cache/pypoetry/virtualenvs/losh-reporter--EO10kDI-py3.9/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/USER/.cache/pypoetry/virtualenvs/losh-reporter--EO10kDI-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/USER/.cache/pypoetry/virtualenvs/losh-reporter--EO10kDI-py3.9/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /loshrdf/sparql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc234802250>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USER/Projects/OSEG/repos/LOSH-Reporter/reporter/cli.py", line 59, in <module>
    main()
  File "/home/USER/Projects/OSEG/repos/LOSH-Reporter/reporter/cli.py", line 52, in main
    report_generator.generate(args)
  File "/home/USER/Projects/OSEG/repos/LOSH-Reporter/reporter/generator.py", line 97, in generate
    results = request(query)
  File "/home/USER/Projects/OSEG/repos/LOSH-Reporter/reporter/core/requester.py", line 48, in request
    response = requests.request('POST', url, data={'query': query})
  File "/home/USER/.cache/pypoetry/virtualenvs/losh-reporter--EO10kDI-py3.9/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/USER/.cache/pypoetry/virtualenvs/losh-reporter--EO10kDI-py3.9/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/USER/.cache/pypoetry/virtualenvs/losh-reporter--EO10kDI-py3.9/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/USER/.cache/pypoetry/virtualenvs/losh-reporter--EO10kDI-py3.9/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /loshrdf/sparql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc234802250>: Failed to establish a new connection: [Errno 111] Connection refused'))




$ # Ok... still something missing, maybe? *reading in README ...* ah, there is something about Fuseki (under # Development) ...
$ cd fuseki
$ docker-compose up
$ # Fails, cause docker is not setup to run as non-root, so:
$ sudo docker-compose up
...
Status: Downloaded newer image for secoresearch/fuseki:latest
Creating fuseki_fuseki_1 ... done
Attaching to fuseki_fuseki_1
fuseki_1  | ###################################
fuseki_1  | Initializing Apache Jena Fuseki
fuseki_1  |
fuseki_1  |
fuseki_1  | ###################################
fuseki_1  | sed: can't create temp file '/fuseki-base/configuration/assembler.ttlXXXXXX': Permission denied
fuseki_1  | sed: can't create temp file '/fuseki-base/configuration/assembler.ttlXXXXXX': Permission denied
fuseki_fuseki_1 exited with code 1
$ # Ups, whats that? lets see ...
$ cd ..
$ grep -r XXXXXX
$ # no output; Here we gave up for now
```

**Comment by traedamatic** [comment]
@hoijui can the chat/call to discuss those issues?

**Comment by hoijui** [comment]
ahh sorry.. yes!

**Comment by traedamatic** [comment]
when do you have time?

**Comment by hoijui** [comment]
wrote you an email on the address you stored here on github

**Comment by moedn** [comment]
@hoijui can this be closed?
